services:
  midpoint:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWD
      PGUSER: $DB_USER
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h db"
      timeout: 10s
      retries: 10
volumes:
  database-data:
